// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RepoPilot.Infrastructure.Persistence;

#nullable disable

namespace RepoPilot.Infrastructure.Migrations
{
    [DbContext(typeof(RepoPilotDbContext))]
    [Migration("20260817193346_EvaluationApprovalSplit")]
    partial class EvaluationApprovalSplit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepoPilot.Domain.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DiffHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.HasIndex("RunId");

                    b.ToTable("approval_decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_approvals_actor_present", "length(btrim(\"DecidedBy\")) > 0");

                            t.HasCheckConstraint("ck_approvals_diff_hash_format", "\"DiffHash\" ~ '^[a-f0-9]{64}$'");
                        });
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.ChangeProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AffectedPaths")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DiffHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("EntriesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RevisionAttempt")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnifiedDiff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "RevisionAttempt");

                    b.ToTable("change_proposals", null, t =>
                        {
                            t.HasCheckConstraint("ck_proposals_diff_hash_format", "\"DiffHash\" ~ '^[a-f0-9]{64}$'");

                            t.HasCheckConstraint("ck_proposals_has_paths", "cardinality(\"AffectedPaths\") >= 1");
                        });
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.EvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovalCoverage")
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("AvgToolCallsPerCompletedTask")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("CompletionRateBaseline")
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("CompletionRateToolEnabled")
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean");

                    b.Property<int>("InteractiveApprovals")
                        .HasColumnType("integer");

                    b.Property<int?>("P50LatencyMs")
                        .HasColumnType("integer");

                    b.Property<int?>("P95LatencyMs")
                        .HasColumnType("integer");

                    b.Property<int>("ProgrammaticApprovals")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RecallAt5")
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ToolSuccessRate")
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.ToTable("evaluation_runs", (string)null);
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.EvaluationTaskResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("EvaluationRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("RelevantFileInTop5")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SuccessConditionMet")
                        .HasColumnType("boolean");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ToolCallCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationRunId", "TaskId", "Mode")
                        .IsUnique();

                    b.ToTable("evaluation_task_results", (string)null);
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.IndexEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkOrdinal")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<int>("IndexVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Symbols")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "IndexVersion");

                    b.HasIndex("RepositoryId", "IndexVersion", "RelativePath", "ChunkOrdinal")
                        .IsUnique();

                    b.ToTable("index_entries", (string)null);
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.RepositoryFixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveIndexVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("EmbeddingDimensions")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModelId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ExcludedFileCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExclusionBreakdown")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("IncludedFileCount")
                        .HasColumnType("integer");

                    b.Property<string>("IndexingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LastIndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TestConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EvaluationRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureStage")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OutcomeReason")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Plan")
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("RevisionAttempt")
                        .HasColumnType("integer");

                    b.Property<string>("SeededTaskId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TerminalOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("ToolsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("VerifyCommandName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationRunId");

                    b.HasIndex("RepositoryId", "Stage");

                    b.ToTable("runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_runs_revision_attempt", "\"RevisionAttempt\" >= 0 AND \"RevisionAttempt\" <= 2");

                            t.HasCheckConstraint("ck_runs_terminal_has_reason", "(\"TerminalOutcome\" IS NULL AND \"OutcomeReason\" IS NULL AND \"EndedAt\" IS NULL) OR (\"TerminalOutcome\" IS NOT NULL AND \"OutcomeReason\" IS NOT NULL AND \"EndedAt\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.RunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsSummary")
                        .HasColumnType("jsonb");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ToolName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("run_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_run_events_sequence", "\"Sequence\" >= 1");
                        });
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("RevisionAttempt")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TimedOut")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "RevisionAttempt");

                    b.ToTable("test_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_results_timeout_not_passed", "NOT (\"TimedOut\" AND \"Passed\")");
                        });
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.WorkingCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsolutePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DestroyedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("working_copies", (string)null);
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("RepoPilot.Domain.Entities.ChangeProposal", null)
                        .WithMany()
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RepoPilot.Domain.Entities.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.ChangeProposal", b =>
                {
                    b.HasOne("RepoPilot.Domain.Entities.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.EvaluationTaskResult", b =>
                {
                    b.HasOne("RepoPilot.Domain.Entities.EvaluationRun", null)
                        .WithMany()
                        .HasForeignKey("EvaluationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.IndexEntry", b =>
                {
                    b.HasOne("RepoPilot.Domain.Entities.RepositoryFixture", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.Run", b =>
                {
                    b.HasOne("RepoPilot.Domain.Entities.RepositoryFixture", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.RunEvent", b =>
                {
                    b.HasOne("RepoPilot.Domain.Entities.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.TestResult", b =>
                {
                    b.HasOne("RepoPilot.Domain.Entities.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoPilot.Domain.Entities.WorkingCopy", b =>
                {
                    b.HasOne("RepoPilot.Domain.Entities.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
