/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered repository fixtures */
        get: operations["listRepositories"];
        put?: never;
        /** Register a repository fixture from the configured allowed set */
        post: operations["registerRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repositoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a repository fixture and its indexing status */
        get: operations["getRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repositoryId}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build or rebuild the retrieval index
         * @description Always a full rebuild with atomic replacement. Searches issued during the rebuild continue to return results from the previous index until the swap completes (FR-003a).
         */
        post: operations["indexRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repositoryId}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the active index (hybrid lexical + vector, RRF-fused) */
        get: operations["searchRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs */
        get: operations["listRuns"];
        put?: never;
        /**
         * Create a coding-agent run
         * @description Accepted immediately and queued. Runs beyond the configured concurrent-execution limit wait in the queue rather than being refused (FR-013a).
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current state and result of a run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abandon a run
         * @description Ends the run as cancelled from any non-terminal stage, including while awaiting approval, and records who abandoned it and when (FR-008a). The working copy is destroyed (FR-026a).
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream run events (Server-Sent Events)
         * @description Push stream of stage transitions and recorded actions. Each frame carries the event sequence as its SSE id. A client reconnecting with Last-Event-ID receives the persisted events after that sequence before attaching to the live stream (FR-028a, SC-013). Also available as a plain JSON list via Accept: application/json.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/proposal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the current change proposal awaiting a decision
         * @description Returns the affected file list and the full unified diff so a reviewer can decide without leaving the review view (SC-004).
         */
        get: operations["getCurrentProposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or reject a proposed change
         * @description The only endpoint that can unlock a file write. diffHash must equal the hash of the proposal being decided; a mismatch means the reviewer is deciding on content other than what will be applied and is refused (FR-020). A proposal that already has a decision is refused regardless of the new decision's value (FR-018).
         */
        post: operations["decideProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the proposed or final diff */
        get: operations["getRunDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read test results for the run */
        get: operations["getRunTests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the committed evaluation task set
         * @description Executes every committed task twice — once retrieval-only and once tool-enabled — through the same orchestrator path as interactive runs, with approval satisfied programmatically and still recorded as an approval decision (FR-034, SC-001).
         */
        post: operations["startEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read evaluation metrics */
        get: operations["getEvaluation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details */
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
        };
        /** @enum {string} */
        RunStage: "created" | "retrieving" | "planning" | "proposing" | "awaiting_approval" | "applying" | "testing" | "succeeded" | "failed" | "rejected" | "cancelled" | "no_change";
        /** @enum {string} */
        TerminalOutcome: "succeeded" | "failed" | "rejected" | "cancelled" | "no_change";
        Repository: {
            /** Format: uuid */
            id: string;
            slug: string;
            displayName?: string;
            /** @enum {string} */
            indexingStatus: "never_indexed" | "indexing" | "indexed" | "failed";
            activeIndexVersion?: number | null;
            includedFileCount?: number;
            excludedFileCount?: number;
            exclusionBreakdown?: {
                [key: string]: number;
            };
            /** Format: date-time */
            lastIndexedAt?: string | null;
            testCommands?: string[];
        };
        IndexingStatus: {
            /** Format: uuid */
            repositoryId?: string;
            /** @enum {string} */
            status?: "indexing" | "indexed" | "failed";
            includedFileCount?: number;
            excludedFileCount?: number;
            exclusionBreakdown?: {
                [key: string]: number;
            };
        };
        RetrievalResult: {
            relativePath: string;
            /** Format: uuid */
            chunkId: string;
            content: string;
            startLine: number;
            endLine: number;
            /** Format: double */
            score: number;
            language?: string | null;
        };
        RunSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            repositoryId: string;
            taskDescription: string;
            stage: components["schemas"]["RunStage"];
            terminalOutcome?: components["schemas"]["TerminalOutcome"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        Run: components["schemas"]["RunSummary"] & {
            outcomeReason?: string | null;
            failureStage?: components["schemas"]["RunStage"] | null;
            revisionAttempt: number;
            toolsEnabled: boolean;
            plan?: string | null;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
        };
        RunEvent: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            sequence: number;
            /** @enum {string} */
            eventType: "stage_changed" | "stage_transition_rejected" | "tool_call" | "plan_produced" | "proposal_created" | "approval_recorded" | "patch_applied" | "tests_completed" | "run_failed" | "run_ended";
            toolName?: string | null;
            argumentsSummary?: Record<string, never> | null;
            /** @enum {string} */
            status: "succeeded" | "failed";
            errorMessage?: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string | null;
            durationMs?: number | null;
        };
        ProposalEntry: {
            path: string;
            /** @enum {string} */
            operation: "create" | "modify";
        };
        ChangeProposal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            revisionAttempt?: number;
            affectedPaths: string[];
            entries?: components["schemas"]["ProposalEntry"][];
            unifiedDiff: string;
            diffHash: string;
            /** @enum {string} */
            decisionStatus: "pending" | "approved" | "rejected";
            /** Format: date-time */
            createdAt?: string;
        };
        ApprovalDecision: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            /** Format: uuid */
            proposalId: string;
            /** @enum {string} */
            decision: "approve" | "reject";
            diffHash: string;
            decidedBy: string;
            /** Format: date-time */
            decidedAt: string;
            /** @enum {string} */
            mode?: "interactive" | "programmatic";
        };
        TestResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            revisionAttempt?: number;
            commandName: string;
            passed: boolean;
            exitCode?: number | null;
            output?: string;
            durationMs: number;
            timedOut: boolean;
        };
        EvaluationRun: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string | null;
            taskCount?: number;
            recallAt5?: number | null;
            completionRateToolEnabled?: number | null;
            completionRateBaseline?: number | null;
            approvalCoverage?: number | null;
            toolSuccessRate?: number | null;
            avgToolCallsPerCompletedTask?: number | null;
            p50LatencyMs?: number | null;
            p95LatencyMs?: number | null;
            /** @description true when approval coverage is below 100% (FR-034, SC-001) */
            flagged?: boolean;
        };
    };
    responses: {
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        RepositoryId: string;
        RunId: string;
        /** @description Identity recorded on the decision or cancellation. Required and non-empty — a request without it is refused (FR-015a, SC-015). Supplied by the deployment and recorded as attributable but not verified; authentication is out of scope for this feature. */
        Actor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"][];
                };
            };
        };
    };
    registerRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Must appear in the configured allowed set (FR-001) */
                    slug: string;
                };
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            /** @description Already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Slug is not in the allowed set — registration refused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    indexRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexing started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexingStatus"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description An index rebuild is already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    searchRepository: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResult"][];
                };
            };
            /** @description Repository has never been indexed, or has zero indexed files */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                repositoryId?: string;
                stage?: components["schemas"]["RunStage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    repositoryId: string;
                    /** @description Required unless seededTaskId is supplied */
                    taskDescription?: string;
                    /** @description Identifier from the committed evaluation task set */
                    seededTaskId?: string;
                    /**
                     * @description false runs the retrieval-only baseline (FR-033)
                     * @default true
                     */
                    toolsEnabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Run created and queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Repository is not indexed, or has zero indexed files */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Neither taskDescription nor seededTaskId supplied */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity recorded on the decision or cancellation. Required and non-empty — a request without it is refused (FR-015a, SC-015). Supplied by the deployment and recorded as attributable but not verified; authentication is out of scope for this feature. */
                "X-Actor": components["parameters"]["Actor"];
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run has already reached a terminal outcome */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                    "application/json": components["schemas"]["RunEvent"][];
                };
            };
        };
    };
    getCurrentProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeProposal"];
                };
            };
            /** @description No proposal exists for this run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    decideProposal: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity recorded on the decision or cancellation. Required and non-empty — a request without it is refused (FR-015a, SC-015). Supplied by the deployment and recorded as attributable but not verified; authentication is out of scope for this feature. */
                "X-Actor": components["parameters"]["Actor"];
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    proposalId: string;
                    /** @enum {string} */
                    decision: "approve" | "reject";
                    /** @description The hash shown to the approver */
                    diffHash: string;
                };
            };
        };
        responses: {
            /** @description Decision recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecision"];
                };
            };
            /** @description Proposal already decided (FR-018) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description diffHash does not match the stored proposal (FR-020a), X-Actor is absent or empty (FR-015a), or programmatic mode was requested for an interactive run (FR-015b) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRunDiff: {
        parameters: {
            query?: {
                /** @description Revision attempt; defaults to the latest */
                attempt?: number;
            };
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeProposal"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRunTests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"][];
                };
            };
        };
    };
    startEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
        };
    };
    getEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
